### ISSUE TITLE
It dosen't work

### ISSUE THREAD

**Issue by dudckd6744** [robin-thomas/serverless-aws-secrets#110]
- serverless.yml
```
service: hellow
frameworkVersion: '3'
custom:
  serverless-aws-secrets:
    secretId: test

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  environment:
    TEST: secret:TEST

functions:
  test:
    handler: index.handler

plugins:
  - serverless-aws-secrets
```
typing `sls aws-secrets --verbose`
It ran right
```
DOTENV: Loading environment variables from .env:
[serverless-aws-secrets]: Running the command: sls aws-secrets
[serverless-aws-secrets]: Loading secret: test in ap-northeast-2
✔ [serverless-aws-secrets]: Secret: TEST, Value: good
```
but  when I typed a console.log , It didn't run right
```
{
   ...
   TEST: 'secret:TEST',
   ...
}
```

how should I do??
can i forgot something?

my environment
language : nodejs
