### ISSUE TITLE
Replace secrets in environment variables defined under function

### ISSUE THREAD

**Issue by robin-thomas** [robin-thomas/serverless-aws-secrets#29]
The plugin replaces the environment variables defined under `provide.environment` key in `serverless.yml`.

Rather than restricting to this, replace the ones that can be defined like:

```
functions:
  function1:
    handler: index.handler
    env:
      ...
```

Also, make `provider.environment` as optional so that the plugin wont crash if its not set.
